// Datos de días inhábiles según tabla de Google Sheets
export const diasInhabilesData = [
  // Ley de Amparo - Aplican para TODOS
  { dia: 'sábados y domingos', fundamento: 'artículo 19 de la Ley de Amparo', tipo: 'finDeSemana', aplicaPara: 'todos' },
  { dia: '1 de enero', fundamento: 'artículo 19 de la Ley de Amparo', fecha: '01-01', aplicaPara: 'todos' },
  { dia: '5 de febrero', fundamento: 'artículo 19 de la Ley de Amparo', fecha: '02-05', aplicaPara: 'todos' },
  { dia: '21 de marzo', fundamento: 'artículo 19 de la Ley de Amparo', fecha: '03-21', aplicaPara: 'todos' },
  { dia: '1 de mayo', fundamento: 'artículo 19 de la Ley de Amparo', fecha: '05-01', aplicaPara: 'todos' },
  { dia: '5 de mayo', fundamento: 'artículo 19 de la Ley de Amparo', fecha: '05-05', aplicaPara: 'todos' },
  { dia: '14 de septiembre', fundamento: 'artículo 19 de la Ley de Amparo', fecha: '09-14', aplicaPara: 'todos' },
  { dia: '16 de septiembre', fundamento: 'artículo 19 de la Ley de Amparo', fecha: '09-16', aplicaPara: 'todos' },
  { dia: '12 de octubre', fundamento: 'artículo 19 de la Ley de Amparo', fecha: '10-12', aplicaPara: 'todos' },
  { dia: '20 de noviembre', fundamento: 'artículo 19 de la Ley de Amparo', fecha: '11-20', aplicaPara: 'todos' },
  { dia: '25 de diciembre', fundamento: 'artículo 19 de la Ley de Amparo', fecha: '12-25', aplicaPara: 'todos' },
  
  // Ley Federal del Trabajo - Días móviles
  { dia: 'primer lunes de febrero', fundamento: 'artículo 74 de la Ley Federal del Trabajo', tipo: 'movil', aplicaPara: 'todos' },
  { dia: 'tercer lunes de marzo', fundamento: 'artículo 74 de la Ley Federal del Trabajo', tipo: 'movil', aplicaPara: 'todos' },
  { dia: 'tercer lunes de noviembre', fundamento: 'artículo 74 de la Ley Federal del Trabajo', tipo: 'movil', aplicaPara: 'todos' },
  
  // Días de cambio de gobierno
  { dia: '1 de diciembre 2000', fundamento: 'artículo 74 de la Ley Federal del Trabajo', fecha: '2000-12-01', aplicaPara: 'todos' },
  { dia: '1 de diciembre 2006', fundamento: 'artículo 74 de la Ley Federal del Trabajo', fecha: '2006-12-01', aplicaPara: 'todos' },
  { dia: '1 de diciembre 2012', fundamento: 'artículo 74 de la Ley Federal del Trabajo', fecha: '2012-12-01', aplicaPara: 'todos' },
  { dia: '1 de diciembre 2018', fundamento: 'artículo 74 de la Ley Federal del Trabajo', fecha: '2018-12-01', aplicaPara: 'todos' },
  { dia: '1 de diciembre 2024', fundamento: 'artículo 74 de la Ley Federal del Trabajo', fecha: '2024-12-01', aplicaPara: 'todos' },
  { dia: '1 de diciembre 2030', fundamento: 'artículo 74 de la Ley Federal del Trabajo', fecha: '2030-12-01', aplicaPara: 'todos' },
  { dia: '1 de diciembre 2036', fundamento: 'artículo 74 de la Ley Federal del Trabajo', fecha: '2036-12-01', aplicaPara: 'todos' },
  { dia: '1 de diciembre 2042', fundamento: 'artículo 74 de la Ley Federal del Trabajo', fecha: '2042-12-01', aplicaPara: 'todos' },
  { dia: '1 de diciembre 2048', fundamento: 'artículo 74 de la Ley Federal del Trabajo', fecha: '2048-12-01', aplicaPara: 'todos' },
  { dia: '1 de diciembre 2054', fundamento: 'artículo 74 de la Ley Federal del Trabajo', fecha: '2054-12-01', aplicaPara: 'todos' },
  { dia: '1 de diciembre 2060', fundamento: 'artículo 74 de la Ley Federal del Trabajo', fecha: '2060-12-01', aplicaPara: 'todos' },
  
  // Circular 7/2024 del Pleno del CJF
  { dia: '27 de marzo 2024', fundamento: 'Circular 7/2024 del Pleno del Consejo de la Judicatura Federal', fecha: '2024-03-27', aplicaPara: 'todos' },
  { dia: '28 de marzo 2024', fundamento: 'Circular 7/2024 del Pleno del Consejo de la Judicatura Federal', fecha: '2024-03-28', aplicaPara: 'todos' },
  { dia: '29 de marzo 2024', fundamento: 'Circular 7/2024 del Pleno del Consejo de la Judicatura Federal', fecha: '2024-03-29', aplicaPara: 'todos' },
  { dia: '1 de octubre 2024', fundamento: 'Circular 7/2024 del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-01', aplicaPara: 'todos' },
  { dia: '1 de noviembre 2024', fundamento: 'Circular 7/2024 del Pleno del Consejo de la Judicatura Federal', fecha: '2024-11-01', aplicaPara: 'todos' },
  
  // Período vacacional julio 2024 - Ley Orgánica
  { dia: '16 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-16', aplicaPara: 'todos' },
  { dia: '17 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-17', aplicaPara: 'todos' },
  { dia: '18 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-18', aplicaPara: 'todos' },
  { dia: '19 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-19', aplicaPara: 'todos' },
  { dia: '20 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-20', aplicaPara: 'todos' },
  { dia: '21 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-21', aplicaPara: 'todos' },
  { dia: '22 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-22', aplicaPara: 'todos' },
  { dia: '23 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-23', aplicaPara: 'todos' },
  { dia: '24 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-24', aplicaPara: 'todos' },
  { dia: '25 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-25', aplicaPara: 'todos' },
  { dia: '26 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-26', aplicaPara: 'todos' },
  { dia: '27 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-27', aplicaPara: 'todos' },
  { dia: '28 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-28', aplicaPara: 'todos' },
  { dia: '29 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-29', aplicaPara: 'todos' },
  { dia: '30 de julio 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-07-30', aplicaPara: 'todos' },
  
  // Período vacacional diciembre 2024 - Ley Orgánica
  { dia: '16 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-16', aplicaPara: 'todos' },
  { dia: '17 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-17', aplicaPara: 'todos' },
  { dia: '18 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-18', aplicaPara: 'todos' },
  { dia: '19 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-19', aplicaPara: 'todos' },
  { dia: '20 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-20', aplicaPara: 'todos' },
  { dia: '21 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-21', aplicaPara: 'todos' },
  { dia: '22 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-22', aplicaPara: 'todos' },
  { dia: '23 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-23', aplicaPara: 'todos' },
  { dia: '24 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-24', aplicaPara: 'todos' },
  { dia: '25 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-25', aplicaPara: 'todos' },
  { dia: '26 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-26', aplicaPara: 'todos' },
  { dia: '27 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-27', aplicaPara: 'todos' },
  { dia: '28 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-28', aplicaPara: 'todos' },
  { dia: '29 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-29', aplicaPara: 'todos' },
  { dia: '30 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-30', aplicaPara: 'todos' },
  { dia: '31 de diciembre 2024', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2024-12-31', aplicaPara: 'todos' },
  
  // Días móviles 2024
  { dia: '05 de febrero 2024', fundamento: 'Artículo 74 de la Ley Federal del Trabajo', fecha: '2024-02-05', aplicaPara: 'todos' }, // Primer lunes febrero

 { dia: '18 de marzo 2024', fundamento: 'Artículo 74 de la Ley Federal del Trabajo', fecha: '2024-03-18', aplicaPara: 'todos' }, // Tercer lunes marzo
  { dia: '18 de noviembre 2024', fundamento: 'Artículo 74 de la Ley Federal del Trabajo', fecha: '2024-11-18', aplicaPara: 'todos' }, // Tercer lunes noviembre
  
  // Período de suspensión por paro - agosto a octubre 2024
  { dia: '19 de agosto 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-08-19', aplicaPara: 'todos' },
  { dia: '20 de agosto 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-08-20', aplicaPara: 'todos' },
  { dia: '21 de agosto 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-08-21', aplicaPara: 'todos' },
  { dia: '22 de agosto 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-08-22', aplicaPara: 'todos' },
  { dia: '23 de agosto 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-08-23', aplicaPara: 'todos' },
  { dia: '24 de agosto 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-08-24', aplicaPara: 'todos' },
  { dia: '25 de agosto 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-08-25', aplicaPara: 'todos' },
  { dia: '26 de agosto 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-08-26', aplicaPara: 'todos' },
  { dia: '27 de agosto 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-08-27', aplicaPara: 'todos' },
  { dia: '28 de agosto 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-08-28', aplicaPara: 'todos' },
  { dia: '29 de agosto 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-08-29', aplicaPara: 'todos' },
  { dia: '30 de agosto 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-08-30', aplicaPara: 'todos' },
  { dia: '31 de agosto 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-08-31', aplicaPara: 'todos' },
  { dia: '1 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-01', aplicaPara: 'todos' },
  { dia: '2 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-02', aplicaPara: 'todos' },
  { dia: '3 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-03', aplicaPara: 'todos' },
  { dia: '4 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-04', aplicaPara: 'todos' },
  { dia: '5 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-05', aplicaPara: 'todos' },
  { dia: '6 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-06', aplicaPara: 'todos' },
  { dia: '7 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-07', aplicaPara: 'todos' },
  { dia: '8 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-08', aplicaPara: 'todos' },
  { dia: '9 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-09', aplicaPara: 'todos' },
  { dia: '10 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-10', aplicaPara: 'todos' },
  { dia: '11 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-11', aplicaPara: 'todos' },
  { dia: '12 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-12', aplicaPara: 'todos' },
  { dia: '13 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-13', aplicaPara: 'todos' },
  { dia: '14 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-14', aplicaPara: 'todos' },
  { dia: '15 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-15', aplicaPara: 'todos' },
  { dia: '16 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-16', aplicaPara: 'todos' },
  { dia: '17 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-17', aplicaPara: 'todos' },
  { dia: '18 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-18', aplicaPara: 'todos' },
  { dia: '19 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-19', aplicaPara: 'todos' },
  { dia: '20 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-20', aplicaPara: 'todos' },
  { dia: '21 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-21', aplicaPara: 'todos' },
  { dia: '22 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-22', aplicaPara: 'todos' },
  { dia: '23 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-23', aplicaPara: 'todos' },
  { dia: '24 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-24', aplicaPara: 'todos' },
  { dia: '25 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-25', aplicaPara: 'todos' },
  { dia: '26 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-26', aplicaPara: 'todos' },
  { dia: '27 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-27', aplicaPara: 'todos' },
  { dia: '28 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-28', aplicaPara: 'todos' },
  { dia: '29 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-29', aplicaPara: 'todos' },
  { dia: '30 de septiembre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-09-30', aplicaPara: 'todos' },
  { dia: '1 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-01', aplicaPara: 'todos' },
  { dia: '2 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-02', aplicaPara: 'todos' },
  { dia: '3 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-03', aplicaPara: 'todos' },
  { dia: '4 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-04', aplicaPara: 'todos' },
  { dia: '5 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-05', aplicaPara: 'todos' },
  { dia: '6 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-06', aplicaPara: 'todos' },
  { dia: '7 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-07', aplicaPara: 'todos' },
  { dia: '8 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-08', aplicaPara: 'todos' },
  { dia: '9 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-09', aplicaPara: 'todos' },
  { dia: '10 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-10', aplicaPara: 'todos' },
  { dia: '11 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-11', aplicaPara: 'todos' },
  { dia: '12 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-12', aplicaPara: 'todos' },
  { dia: '13 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-13', aplicaPara: 'todos' },
  { dia: '14 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-14', aplicaPara: 'todos' },
  { dia: '15 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-15', aplicaPara: 'todos' },
  { dia: '16 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-16', aplicaPara: 'todos' },
  { dia: '17 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-17', aplicaPara: 'todos' },
  { dia: '18 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-18', aplicaPara: 'todos' },
  { dia: '19 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-19', aplicaPara: 'todos' },
  { dia: '20 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-20', aplicaPara: 'todos' },
  { dia: '21 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-21', aplicaPara: 'todos' },
  { dia: '22 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-22', aplicaPara: 'todos' },
  { dia: '23 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-23', aplicaPara: 'todos' },
  { dia: '24 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-24', aplicaPara: 'todos' },
  { dia: '25 de octubre 2024', fundamento: 'diversas circulares del Pleno del Consejo de la Judicatura Federal', fecha: '2024-10-25', aplicaPara: 'todos' },
  
 // === DÍAS DE 2022 ===
  
  // Días móviles 2022
  { dia: '7 de febrero 2022', fundamento: 'Artículo 74 de la Ley Federal del Trabajo', fecha: '2022-02-07', aplicaPara: 'todos' },
  { dia: '21 de marzo 2022', fundamento: 'Artículo 74 de la Ley Federal del Trabajo', fecha: '2022-03-21', aplicaPara: 'todos' },
  { dia: '21 de noviembre 2022', fundamento: 'Artículo 74 de la Ley Federal del Trabajo', fecha: '2022-11-21', aplicaPara: 'todos' },
// CIRCULAR 5/2022 - Semana Santa
  { dia: '13 de abril 2022', fundamento: 'Circular 5/2022 del Pleno del Consejo de la Judicatura Federal', fecha: '2022-04-13', aplicaPara: 'todos' },
  { dia: '14 de abril 2022', fundamento: 'Circular 5/2022 del Pleno del Consejo de la Judicatura Federal', fecha: '2022-04-14', aplicaPara: 'todos' },
  { dia: '15 de abril 2022', fundamento: 'Circular 5/2022 del Pleno del Consejo de la Judicatura Federal', fecha: '2022-04-15', aplicaPara: 'todos' },
  
  // CIRCULAR 5/2022 - Otros días
  { dia: '6 de mayo 2022', fundamento: 'Circular 5/2022 del Pleno del Consejo de la Judicatura Federal', fecha: '2022-05-06', aplicaPara: 'todos' },
  { dia: '15 de septiembre 2022', fundamento: 'Circular 5/2022 del Pleno del Consejo de la Judicatura Federal', fecha: '2022-09-15', aplicaPara: 'todos' },
  { dia: '31 de octubre 2022', fundamento: 'Circular 5/2022 del Pleno del Consejo de la Judicatura Federal', fecha: '2022-10-31', aplicaPara: 'todos' },
  { dia: '1 de noviembre 2022', fundamento: 'Circular 5/2022 del Pleno del Consejo de la Judicatura Federal', fecha: '2022-11-01', aplicaPara: 'todos' },
  { dia: '2 de noviembre 2022', fundamento: 'Circular 5/2022 del Pleno del Consejo de la Judicatura Federal', fecha: '2022-11-02', aplicaPara: 'todos' },
  
  // Período vacacional julio 2022
  { dia: '16 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-16', aplicaPara: 'todos' },
  { dia: '17 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-17', aplicaPara: 'todos' },
  { dia: '18 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-18', aplicaPara: 'todos' },
  { dia: '19 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-19', aplicaPara: 'todos' },
  { dia: '20 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-20', aplicaPara: 'todos' },
  { dia: '21 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-21', aplicaPara: 'todos' },
  { dia: '22 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-22', aplicaPara: 'todos' },
  { dia: '23 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-23', aplicaPara: 'todos' },
  { dia: '24 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-24', aplicaPara: 'todos' },
  { dia: '25 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-25', aplicaPara: 'todos' },
  { dia: '26 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-26', aplicaPara: 'todos' },
  { dia: '27 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-27', aplicaPara: 'todos' },
  { dia: '28 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-28', aplicaPara: 'todos' },
  { dia: '29 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-29', aplicaPara: 'todos' },
  { dia: '30 de julio 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-07-30', aplicaPara: 'todos' },
  
  // Período vacacional diciembre 2022
  { dia: '16 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-16', aplicaPara: 'todos' },
  { dia: '17 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-17', aplicaPara: 'todos' },
  { dia: '18 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-18', aplicaPara: 'todos' },
  { dia: '19 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-19', aplicaPara: 'todos' },
  { dia: '20 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-20', aplicaPara: 'todos' },
  { dia: '21 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-21', aplicaPara: 'todos' },
  { dia: '22 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-22', aplicaPara: 'todos' },
  { dia: '23 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-23', aplicaPara: 'todos' },
  { dia: '24 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-24', aplicaPara: 'todos' },
  { dia: '25 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-25', aplicaPara: 'todos' },
  { dia: '26 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-26', aplicaPara: 'todos' },
  { dia: '27 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-27', aplicaPara: 'todos' },
  { dia: '28 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-28', aplicaPara: 'todos' },
  { dia: '29 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-29', aplicaPara: 'todos' },
  { dia: '30 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-30', aplicaPara: 'todos' },
  { dia: '31 de diciembre 2022', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2022-12-31', aplicaPara: 'todos' },
  
  // === DÍAS DE 2023 ===
  
  // Días móviles 2023
  { dia: '6 de febrero 2023', fundamento: 'Artículo 74 de la Ley Federal del Trabajo', fecha: '2023-02-06', aplicaPara: 'todos' },
  { dia: '20 de marzo 2023', fundamento: 'Artículo 74 de la Ley Federal del Trabajo', fecha: '2023-03-20', aplicaPara: 'todos' },
  { dia: '20 de noviembre 2023', fundamento: 'Artículo 74 de la Ley Federal del Trabajo', fecha: '2023-11-20', aplicaPara: 'todos' },
  
// CIRCULAR 12/2023 - Semana Santa
  { dia: '5 de abril 2023', fundamento: 'Circular 12/2023 del Pleno del Consejo de la Judicatura Federal', fecha: '2023-04-05', aplicaPara: 'todos' },
  { dia: '6 de abril 2023', fundamento: 'Circular 12/2023 del Pleno del Consejo de la Judicatura Federal', fecha: '2023-04-06', aplicaPara: 'todos' },
  { dia: '7 de abril 2023', fundamento: 'Circular 12/2023 del Pleno del Consejo de la Judicatura Federal', fecha: '2023-04-07', aplicaPara: 'todos' },
  
  // CIRCULAR 12/2023 - Otros días
  { dia: '15 de septiembre 2023', fundamento: 'Circular 12/2023 del Pleno del Consejo de la Judicatura Federal', fecha: '2023-09-15', aplicaPara: 'todos' },
  { dia: '1 de noviembre 2023', fundamento: 'Circular 12/2023 del Pleno del Consejo de la Judicatura Federal', fecha: '2023-11-01', aplicaPara: 'todos' },
  { dia: '2 de noviembre 2023', fundamento: 'Circular 12/2023 del Pleno del Consejo de la Judicatura Federal', fecha: '2023-11-02', aplicaPara: 'todos' },
  { dia: '3 de noviembre 2023', fundamento: 'Circular 12/2023 del Pleno del Consejo de la Judicatura Federal', fecha: '2023-11-03', aplicaPara: 'todos' },
  // Período vacacional julio 2023
  { dia: '16 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-16', aplicaPara: 'todos' },
  { dia: '17 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-17', aplicaPara: 'todos' },
  { dia: '18 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-18', aplicaPara: 'todos' },
  { dia: '19 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-19', aplicaPara: 'todos' },
  { dia: '20 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-20', aplicaPara: 'todos' },
  { dia: '21 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-21', aplicaPara: 'todos' },
  { dia: '22 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-22', aplicaPara: 'todos' },
  { dia: '23 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-23', aplicaPara: 'todos' },
  { dia: '24 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-24', aplicaPara: 'todos' },
  { dia: '25 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-25', aplicaPara: 'todos' },
  { dia: '26 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-26', aplicaPara: 'todos' },
  { dia: '27 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-27', aplicaPara: 'todos' },
  { dia: '28 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-28', aplicaPara: 'todos' },
  { dia: '29 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-29', aplicaPara: 'todos' },
  { dia: '30 de julio 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-07-30', aplicaPara: 'todos' },
  
  // Período vacacional diciembre 2023
  { dia: '16 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-16', aplicaPara: 'todos' },
  { dia: '17 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-17', aplicaPara: 'todos' },
  { dia: '18 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-18', aplicaPara: 'todos' },
  { dia: '19 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-19', aplicaPara: 'todos' },
  { dia: '20 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-20', aplicaPara: 'todos' },
  { dia: '21 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-21', aplicaPara: 'todos' },
  { dia: '22 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-22', aplicaPara: 'todos' },
  { dia: '23 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-23', aplicaPara: 'todos' },
  { dia: '24 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-24', aplicaPara: 'todos' },
  { dia: '25 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-25', aplicaPara: 'todos' },
  { dia: '26 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-26', aplicaPara: 'todos' },
  { dia: '27 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-27', aplicaPara: 'todos' },
  { dia: '28 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-28', aplicaPara: 'todos' },
  { dia: '29 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-29', aplicaPara: 'todos' },
  { dia: '30 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-30', aplicaPara: 'todos' },
  { dia: '31 de diciembre 2023', fundamento: 'Artículo 75 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2023-12-31', aplicaPara: 'todos' },
 // === DÍAS DE 2025 ===
  
  // Período vacacional julio 2025 - Ley Orgánica
  { dia: '16 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-16', aplicaPara: 'todos' },
  { dia: '17 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-17', aplicaPara: 'todos' },
  { dia: '18 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-18', aplicaPara: 'todos' },
  { dia: '19 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-19', aplicaPara: 'todos' },
  { dia: '20 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-20', aplicaPara: 'todos' },
  { dia: '21 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-21', aplicaPara: 'todos' },
  { dia: '22 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-22', aplicaPara: 'todos' },
  { dia: '23 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-23', aplicaPara: 'todos' },
  { dia: '24 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-24', aplicaPara: 'todos' },
  { dia: '25 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-25', aplicaPara: 'todos' },
  { dia: '26 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-26', aplicaPara: 'todos' },
  { dia: '27 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-27', aplicaPara: 'todos' },
  { dia: '28 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-28', aplicaPara: 'todos' },
  { dia: '29 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-29', aplicaPara: 'todos' },
  { dia: '30 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-30', aplicaPara: 'todos' },
  { dia: '31 de julio 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-07-31', aplicaPara: 'todos' },
  
  // Período vacacional diciembre 2025 - Ley Orgánica
  { dia: '16 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-16', aplicaPara: 'todos' },
  { dia: '17 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-17', aplicaPara: 'todos' },
  { dia: '18 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-18', aplicaPara: 'todos' },
  { dia: '19 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-19', aplicaPara: 'todos' },
  { dia: '20 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-20', aplicaPara: 'todos' },
  { dia: '21 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-21', aplicaPara: 'todos' },
  { dia: '22 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-22', aplicaPara: 'todos' },
  { dia: '23 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-23', aplicaPara: 'todos' },
  { dia: '24 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-24', aplicaPara: 'todos' },
  { dia: '25 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-25', aplicaPara: 'todos' },
  { dia: '26 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-26', aplicaPara: 'todos' },
  { dia: '27 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-27', aplicaPara: 'todos' },
  { dia: '28 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-28', aplicaPara: 'todos' },
  { dia: '29 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-29', aplicaPara: 'todos' },
  { dia: '30 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-30', aplicaPara: 'todos' },
  { dia: '31 de diciembre 2025', fundamento: 'Artículo 76 de la Ley Orgánica del Poder Judicial de la Federación', fecha: '2025-12-31', aplicaPara: 'todos' },
  
  // Días móviles 2025
  { dia: '3 de febrero 2025', fundamento: 'Artículo 74 de la Ley Federal del Trabajo', fecha: '2025-02-03', aplicaPara: 'todos' },
  { dia: '17 de noviembre 2025', fundamento: 'Artículo 74 de la Ley Federal del Trabajo', fecha: '2025-11-17', aplicaPara: 'todos' },
  
  // Circular 1/2024 - Semana Santa 2025
  { dia: '17 de abril 2025', fundamento: 'Circular 1/2025 del Pleno del Consejo de la Judicatura Federal', fecha: '2025-04-17', aplicaPara: 'todos' },
  { dia: '18 de abril 2025', fundamento: 'Circular 1/2025 del Pleno del Consejo de la Judicatura Federal', fecha: '2025-04-18', aplicaPara: 'todos' },
  { dia: '19 de abril 2025', fundamento: 'Circular 1/2025 del Pleno del Consejo de la Judicatura Federal', fecha: '2025-04-19', aplicaPara: 'todos' }
];